typography_spectrum: 0.60846
color:
  brandColors:
    - '#453c7b'
    - '#754769'
    - '#3d747a'
    - '#827d43'
    - '#915d9a'
  brandStrength: 0.125
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.386160877533257
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Maxime
  email: maxime.fudym@gmail.com
name: 'votre futur T3 '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
